let prodArr = [
  {
    name: "Tournus 4-6-Person Extendable Solid Rubberwood Dining Table Set by iNSPIRE Q Classic",
    img_url: "https://bit.ly/3sanVR4",
    imgArr: [
      "https://bit.ly/3OVA5qZ",
      "https://bit.ly/3w5hfF8",
      "https://bit.ly/3w2CXtB",
      "https://bit.ly/3KLpPOC",
      "https://bit.ly/3sxYo4T",
    ],
    ratings: "⭐️⭐️⭐️⭐️⭐️",
    price: "1381.49",
    details:
      "Bring a sense of sophistication to your dining room with this Extendable Solid Rubberwood Dining Table Set. This sturdy table and chairs are crafted with the perfect combination of antique-white finish base and matching wood grain veneer tabletop and chair slat back. You'll love the dining table with a curved-in support leg, which provides more room for people at the table. The solid rubberwood construction is sturdy and more durable than other woods. This matching dining table and chairs are perfect for hosting farm-fresh small family dinners. This table can be extended to seat 6 comfortably or up to 8 for dinner parties and plenty of space for 4 seats for family meals. It's the perfect size for entertaining or everyday use. ",
    desc: "You'll love the dining table with a curved-in support leg, which provides more room for people at the table",
    info: {
      reviews: 500,
      discount: 20,
      brand: " iNSPIRE Q",
      availability: true,
      style: "Traditional",
    },
  },
  {
    name: "The Gray Barn Hillcrest 3-Piece Storage Nook",
    img_url: "https://bit.ly/3OW4zsU",
    imgArr: [
      "https://bit.ly/3MO74vp",
      "https://bit.ly/3kC1iAS",
      "https://bit.ly/38OpnBQ",
      "https://bit.ly/3LHlSvN",
      "https://bit.ly/3KHHlU5",
    ],
    ratings: "⭐️⭐️⭐️⭐️⭐️",
    price: " 790.19",
    details:
      "Create a cozy spot in any corner of your kitchen perfect for meals and conversation with this charming nook. This three piece set provides extra storage, space and wonderful function; with seating for five comfortably. Your choice of a classic White or Black finish will bring country manor elegance to your existing home décor.",
    desc: "Create a cozy spot in any corner of your kitchen perfect for meals and conversation with this charming nook",
    info: {
      reviews: 200,
      discount: 40,
      brand: "The Gray Barn",
      availability: true,
      style: "  Casual ",
    },
  },
  {
    name: "Simple Living Maura Buffet - Charcoal Gray",
    img_url: "https://bit.ly/3vID0LS",
    imgArr: [
      "https://bit.ly/3Fm2XV2",
      "https://bit.ly/3yeO0T4",
      "https://bit.ly/3MLuEJe",
      "https://bit.ly/3kGdkcO",
      "https://bit.ly/38PvoOF",
    ],
    ratings: "⭐️⭐️⭐️⭐️",
    price: "359.19",
    details:
      "Featuring a pristine white shade with a gold-toned finish that elevates the aesthetic appeal of your traditionally styled home, this piece provides ample storage space for your television, electronics, dinnerware, and other essentials. Give your living room a makeover with this sleek Maura buffet from Simple Living.  ",
    desc: "Featuring a pristine white shade with a gold-toned finish that elevates the aesthetic appeal of your traditionally styled home.",
    info: {
      reviews: 136,
      discount: 20,
      brand: "Simple Living",
      availability: true,
      style: "Southwestern",
    },
  },
  {
    name: "Furniture of America Tern Modern 5-Bottle Mobile Wine Cabinet - Light Hickory",
    img_url: "https://bit.ly/3vHlTuc",
    imgArr: [
      "https://bit.ly/3w2J8xN",
      "https://bit.ly/3s8cdGY",
      "https://bit.ly/37cRdY7",
      "https://bit.ly/3LL4VR0",
      "https://bit.ly/39qnPOQ",
    ],
    ratings: "⭐️⭐️⭐️⭐️⭐️",
    price: "365.99",
    details:
      "Modern elegance has a way of invigorating a space with excitement. This mobile buffet table displays a playful diagonal accent with a practical use as a wine bottle holder. A hanging stemware rack, one dual-side access shelf, two open side shelves, and two cabinet shelves add to the storage capabilities of this buffet.",
    desc: "This mobile buffet table displays a playful diagonal accent with a practical use as a wine bottle holder",
    info: {
      reviews: 29,
      discount: 27,
      brand: " Furniture of America",
      availability: true,
      style: " 3. Mid-Century Modern",
    },
  },
  {
    name: "Simple Living Dawson Circle Front Cabinet - Charcoal Grey",
    img_url: "https://bit.ly/3LHroOU",
    imgArr: [
      "https://bit.ly/3w3ywyz",
      "https://bit.ly/3Fc67ui",
      "https://bit.ly/38Pxdvl",
      "https://bit.ly/3LCScQp",
      "https://bit.ly/3LIxm1X",
    ],
    ratings: "⭐️⭐️⭐️⭐️",
    price: " 303.99",
    details:
      "Stash your precious chinaware and glassware in this Dawson cabinet. Circular patterns on the front panels add an aesthetic appearance to the light grey, charcoal grey, white or midnight blue finish of this cabinet. Equipped with a top drawer and a roomy lower compartment with an adjustable shelf, this cabinet eases your task of sorting out dining essentials.",
    desc: "",
    info: {
      reviews: 200,
      discount: 5,
      brand: "Simple Living",
      availability: true,
      style: "Southwestern",
    },
  },
  {
    name: "Furniture of America Darion Rustic Antique White Buffet with Wine Rack",
    img_url: "https://bit.ly/3kDVNBT",
    imgArr: [
      "https://bit.ly/3LHUvS5",
      "https://bit.ly/3Fg3dol",
      "https://bit.ly/3vHyYni",
      "https://bit.ly/3kDVNBT",
      "https://bit.ly/3LHUvS5",
    ],
    ratings: "⭐️⭐️⭐️⭐️",
    price: "1283.99",
    details:
      "Showcasing a tasteful and functional design, this wood buffet with wine rack makes entertaining in a casual space pleasant and easy. From the Darion collection by Furniture of America, this two-tone server is built from wood and wood veneers and given a contrasting dual finish palette of antique white and oak. Storage space in two drawers and four shelves includes a four-shelf wine rack for standard size wine bottles. Louvered style cabinet fronts charm this buffet with a truly in-character rustic country look. Dark metal handles and an oak top surface make the distressed finish of the sideboard take center stage.",
    desc: "Showcasing a tasteful and functional design, this wood buffet with wine rack makes entertaining in a casual space pleasant and easy",
    info: {
      reviews: 300,
      discount: 20,
      brand: "Furniture of America",
      availability: true,
      style: "Casualy",
    },
  },
  {
    name: "Furniture of America Timm Farmhouse White Solid Wood Dining Server",
    img_url: "https://bit.ly/3w2pxh8",
    imgArr: [
      "https://bit.ly/3LIaNe0",
      "https://bit.ly/3KJXwjw",
      "https://bit.ly/3LNClP2",
      "https://bit.ly/3w79tuF",
      "https://bit.ly/3w2pxh8",
    ],
    ratings: "⭐️⭐️⭐️⭐️",
    price: "1076.39",
    details:
      "From the Timm collection of Furniture of America comes this transitional dining server, finished in a distressed antique white tone that lends itself perfectly to a cheery French country home or beachside cottage. Place this elegant furniture piece in your dining room to store your fine dishes, pitchers, and bowls all within reach and tucked inside two spacious drawers and two cabinets. Between the cabinets is a convenient open area with a 12-slot wine bottle storage and three stemware racks that make it easy to slide out a wine glass for company. In addition, this server has round metal hardware and squared turned legs that lend a vintage aesthetic",
    desc: "From the Timm collection of Furniture of America comes this transitional dining server, finished in a distressed antique white tone that lends itself perfectly to a cheery French country home or beachside cottage",
    info: {
      reviews: 250,
      discount: 20,
      brand: "Furniture of America",
      availability: true,
      style: "Farm House",
    },
  },
  {
    name: "Modern White Entryway Sideboard Storage Cabinet with 4 Doors",
    img_url: "https://bit.ly/3KHOLXo",
    imgArr: [
      "https://bit.ly/3kJo8qg",
      "https://bit.ly/3vHD92s",
      "https://bit.ly/3vGyA8i",
      "https://bit.ly/3vZTtul",
      "https://bit.ly/3vH69qT",
    ],
    ratings: "⭐️⭐️⭐️⭐️",
    price: " 349.80",
    details:
      "The outstanding metal handle is simple and versatile for various home decorations. The buffet cabinet sideboard is carefully crafted from high-quality medium density fiberboard, stable and durable.4-door storage design could be used as a buffet in the kitchen to providing enough storage space. This combination of practical and ornamental design creates a beautiful accent console cabinet that will complement any living room, dining room, or hallway.",
    desc: "The outstanding metal handle is simple and versatile for various home decorations",
    info: {
      reviews: 300,
      discount: 5,
      brand: "Parrot Uncle",
      availability: true,
      style: "Southwestern",
    },
  },
  {
    name: "ZLINE 36 in. 22.5 cu. ft Freestanding French Door Refrigerator with Ice Maker (RFM-36)",
    img_url: "https://bit.ly/3saCJzw",
    imgArr: [
      "https://bit.ly/3kFvCec",
      "https://bit.ly/3FiHsV8",
      "https://bit.ly/38S6Mos",
      "https://bit.ly/3Feb5GO",
      "https://bit.ly/37ZjTo6",
    ],
    ratings: "⭐️⭐️⭐️⭐️",
    price: " 3999.95",
    details:
      "The outstanding metal handle is simple and versatile for various home decorations......",
    desc: "The outstanding metal handle is simple and versatile for various home decorations",
    info: {
      reviews: 300,
      discount: 30,
      brand: "Zline Kitchen and Bath",
      availability: true,
      style: "Modern & Contemporary",
    },
  },
  {
    name: "Beverage Refrigerator Cooler-145 Can Mini Fridge Clear Front",
    img_url: "https://bit.ly/3vHUbNP",
    imgArr: [
      "https://bit.ly/3vVS5ZC",
      "https://bit.ly/3kFxCmI",
      "https://bit.ly/3vFkLao",
      "https://bit.ly/39vgRIp",
      "https://bit.ly/39D9iQ7",
    ],
    ratings: "⭐️⭐️⭐️⭐️",
    price: "426.07",
    details:
      " If you want to your beer or soda to have a good taste, 4.5 Cu.Ft. Beverage Refrigerator provides plenty of storage for your favorite snacks and drinks, it's ideal for your entertaining or retail merchandising needs. Unlike many budget beverage refrigerators, the 60 can black frame beverage refrigerator utilizes premium features and design to provide a sleek showcase that will be centerpiece of any space.With its powerful compressor and internal air-cooled system, this beverage refrigerator creates an evenly-cooled space ensuring consistent temperatures throughout the beverage refrigerator.",
    desc: "arge digital display for quick monitoring and setting of any temperature",
    info: {
      reviews: 235,
      discount: 10,
      brand: "Waterford",
      availability: true,
      style: "Modern & Contemporary",
    },
  },
  {
    name: "Thor Kitchen 24-inch Indoor/Outdoor Under-counter Refrigerator Drawers",
    img_url: "https://bit.ly/3LIKx2V",
    imgArr: [
      "https://bit.ly/3kFAwYE",
      "https://bit.ly/3KHrNzM",
      "https://bit.ly/3w6cFXl",
      "https://bit.ly/3LIKx2V",
      "https://bit.ly/3OW30ex",
    ],
    ratings: "⭐️⭐️⭐️⭐️",
    price: "1599.00",
    details:
      "Expand your fridge space with this convenient under-counter refrigerator drawer unit from Thor Kitchen. This piece features two large stainless steel drawers with an included stainless steel basket to keep foods organized. This refrigerator is safe for use indoors or outdoors for versatile placement.",
    desc: " Expand your fridge space with this convenient under-counter refrigerator drawer unit from Thor Kitchen",
    info: {
      reviews: 100,
      discount: 10,
      brand: "Thor Kitchen",
      availability: true,
      style: " 3. Mid-Century Modern",
    },
  },
  {
    name: "NewAir Premium Built-in Outdoor Refrigerator 160 Can Storage Beverage Cooler Center Fridge for Patio - Stainless Steel",
    img_url:
      "https://ak1.ostkcdn.com/images/products/is/images/direct/db390afb2024234ecb7d04c059bfc44672c2478a/NewAir-Premium-Built-in-Outdoor-Refrigerator-160-Can-Storage-Beverage-Cooler-Center-Fridge-for-Patio---Stainless-Steel.jpg?impolicy=medium",
    imgArr: [
      "https://ak1.ostkcdn.com/images/products/is/images/direct/d5fee9c0596d590aaaa576653258212d2de28cc3/NewAir-Premium-Built-in-Outdoor-Refrigerator-160-Can-Storage-Beverage-Cooler-Center-Fridge-for-Patio---Stainless-Steel.jpg?impolicy=medium",
      "https://ak1.ostkcdn.com/images/products/is/images/direct/6be685645e68efae688969beee31a1991a039b60/NewAir-Premium-Built-in-Outdoor-Refrigerator-160-Can-Storage-Beverage-Cooler-Center-Fridge-for-Patio---Stainless-Steel.jpg?impolicy=medium",
      "https://ak1.ostkcdn.com/images/products/is/images/direct/798b792de2cb5d59df39475d3e3d7b86debcfab8/NewAir-Premium-Built-in-Outdoor-Refrigerator-160-Can-Storage-Beverage-Cooler-Center-Fridge-for-Patio---Stainless-Steel.jpg?impolicy=medium",
      "https://ak1.ostkcdn.com/images/products/is/images/direct/03b7b2327f7f68aee00b5c4c7f16158cc0e62598/NewAir-Premium-Built-in-Outdoor-Refrigerator-160-Can-Storage-Beverage-Cooler-Center-Fridge-for-Patio---Stainless-Steel.jpg?impolicy=medium",
      "https://ak1.ostkcdn.com/images/products/is/images/direct/46e30b50589efe73ac531e96ca53dc39b711cf38/NewAir-Premium-Built-in-Outdoor-Refrigerator-160-Can-Storage-Beverage-Cooler-Center-Fridge-for-Patio---Stainless-Steel.jpg?impolicy=medium",
    ],
    ratings: "⭐️⭐️⭐️⭐️",
    price: " 1180.37",
    details:
      "Meet the perfect addition to any outdoor entertainment space: the NewAir 24” Built-In 160 Can Outdoor Beverage Fridge. With its durable, food-grade, 304 stainless-steel finish, the NewAir 24” Outdoor Fridge is ready for your backyard. Whether you experience intense heat, rain, ice or snow, it will stand up to some of the toughest outdoor weather conditions. Chill all your favorite beverages, or store food near the barbecue, to save time while grilling. ",
    desc: "Maintains temperatures as low as 32°F even in very hot climates, unlike normal outdoor fridges",
    info: {
      reviews: 100,
      discount: 20,
      brand: "NewAir",
      availability: true,
      style: "",
    },
  },
  {
    name: "Caynel 4-Liter Portable Mini Fridge for Home, Office and Car, AC/DC Thermoelectric System",
    img_url: "https://bit.ly/3vG9OFj",
    imgArr: [
      "https://bit.ly/3vFVa0P",
      "https://bit.ly/3OWAOIA",
      "https://bit.ly/3FivRFl",
      "https://bit.ly/3kBWJGS",
      "https://bit.ly/3FcGf1i",
    ],
    ratings: "⭐️⭐️⭐️⭐️",
    price: "69.99",
    details:
      "Antarctic Star Refrigerator gives you a cool feeling, this compact refrigerator is perfect for dorm rooms, office break rooms, RVs, bars, and other places where space is tight.The appearance is full of fashionable feeling, a refrigerator not only protects and stores food but does so efficiently and affordably. ",
    desc: "3.2 CU FT Compact Mini Refrigerator Separate Freezer, Small Fridge - Overstock - 32893969",
    info: {
      reviews: 250,
      discount: 30,
      brand: "Zline Kitchen ",
      availability: true,
      style: "Modern & Contemporary",
    },
  },
  {
    name: "Berlinger Haus 10-Piece Kitchen Cookware Set Emerald Collection",
    img_url: "https://bit.ly/37YHhSH",
    imgArr: [
      "https://bit.ly/3OW7Kkl",
      "https://bit.ly/3kECPLn",
      "https://bit.ly/3w6ohJF",
      "https://bit.ly/37YHhSH",
      "https://bit.ly/3w6ohJF",
    ],
    ratings: "⭐️⭐️⭐️⭐️",
    price: "232.19",
    details:
      "Aluminum cookware crafted to support amazing meals and unforgettable times spent with family and friends. Founded for those who love spending time crafting healthy meals for their kids and high-end courses for friends the Berlinger Haus Aluminum Cookware Set offers the ideal balance of style, versatility, and durable craftsmanship. From our non-stick, triple-coated surfaces to our heat-resistant, soft touch handles, we've thought of everything you'll need to open up your cookbook and try out new recipes. Make cooking fun, enhance the look of your kitchen, and make every meal at home memorable once again. Designed to Fit Your Everyday Life Here at Berlinger Haus we understand that the people using our products are making dinners for their friends and family, which means you want them to fit your cookbook and your lifestyle. That's why we offer our cookware in a variety of vibrant, luxury colors and set variations to support your favorite recipes, holiday gatherings, and special moments spent with those you love. Enjoy cooking with style with a luxury set of Berlinger Haus cookware designed for elegance, versatility, and convenience. Get one today by clicking Add to Cart above and add a touch of class to your kitchen.",
    desc: " Berlinger Haus Aluminum Cookware Set offers the ideal balance of style, versatility, and durable craftsmanship",
    info: {
      reviews: 270,
      discount: 10,
      brand: " Berlinger Haus",
      availability: true,
      style: "Modern & Contemporary",
    },
  },
  {
    name: "Deco Chef 12 Piece Stainless Steel Knife Set with Storage Block",
    img_url: "https://bit.ly/3OYXUxU",
    imgArr: [
      "https://bit.ly/389ngIS",
      "https://bit.ly/3KIWWmi",
      "https://bit.ly/3MTEjOa",
      "https://bit.ly/3MPjQK7",
      "https://bit.ly/3LIXR7B",
    ],
    ratings: "⭐️⭐️⭐️⭐️",
    price: "  37.99",
    details:
      "Deco Chef offers a 12-Piece Knife Set to outfit your kitchen with cutlery essentials. Each blade is comprised of high-grade stainless steel that is guaranteed to never rust and to hold its sharp cutting edge longer. Thanks to their high strength, you can confidently tackle each cutting, chopping, slicing, and dicing task with ease. And because they are stainless steel, hand wash cleanup is simple!",
    desc: "Each knife handle is formed from strong ABS with a 430SS Bolster. Balanced, comfortable to hold, and ergonomically easy to hold, these handles allow you to make precision.",
    info: {
      reviews: 165,
      discount: 10,
      brand: "Deco LLC",
      availability: true,
      style: "Modern & Contemporary",
    },
  },
  {
    name: "Deco Chef 5.5 QT Kitchen Stand Mixer, 550W 8-Speed Motor, includes 3 Mixing Attachments",
    img_url: "https://bit.ly/3w4weiD",
    imgArr: [
      "https://bit.ly/3w80N7j",
      "https://bit.ly/39D2D8y",
      "https://bit.ly/3w6seOC",
      "https://bit.ly/3LMJEq3",
      "https://bit.ly/3FuBalr",
    ],
    ratings: "⭐️⭐️⭐️⭐️",
    price: 89.99,
    details:
      "The Deco Chef 5.5 QT Kitchen Stand Mixer is a stylish and user-friendly planetary standing mixer that is the perfect complement to the avid baker and cooking enthusiast at home - combine, mix, beat, cream, knead, and whip your favorite deserts and dinner dishes into culinary perfection!",
    desc: "Featuring a powerful 550-watt motor, this standing mixer is able to power through the toughest doughs using 8-speed settings with pulse functionality",
    info: {
      reviews: 150,
      discount: 10,
      brand: "DEDO LLC",
      availability: true,
      style: "Modern & Contemporary",
    },
  },
  {
    name: "HOMCOM Stand Mixer with 6+1P Speed, 600W Tilt Head Kitchen Electric Mixer with 6 Qt Stainless Steel Mixing Bowl",
    img_url: "https://bit.ly/3vHaHgR",
    imgArr: [
      "https://bit.ly/3yf1JJI",
      "https://bit.ly/3sboGcR",
      "https://bit.ly/3N8eHNF",
      "https://bit.ly/3kDkTB1",
      "https://bit.ly/3kE3uIb",
    ],
    ratings: "⭐️⭐️⭐️⭐️",
    price: "109.99",
    details:
      "A sound mixer is a necessary boost for perfect baking treats. This stand mixer works fast and frees your hands to work on other dishes. This HOMCOM electric mixer with versatile mixing heads and speeds is a great assistant when you make cakes, bread, cookies, pastry, muffins, and waffles. The 6QT capacity can serve your whole family in a single batch, and the compact size fits a limited countertop. This electric mixer will be one of the best pieces of equipment in your kitchen.",
    desc: "A sound mixer is a necessary boost for perfect baking treats. This stand mixer works fast and frees your hands to work on other dishes. ",
    info: {
      reviews: 100,
      discount: 30,
      brand: "Homcom",
      availability: true,
      style: "Formal",
    },
  },
  {
    name: "HOMCOM 5-in-1 Electric Hand Mixer, Handheld Mixer with Measuring Cup, 300W Immersion Blender with 5+1P Speeds",
    img_url: "https://bit.ly/3yaRrdl",
    imgArr: [
      "https://bit.ly/3KN8vJ4",
      "https://bit.ly/3OXM3jF",
      "https://bit.ly/3OXLZ3p",
      "https://bit.ly/3s9iX7u",
      "https://bit.ly/3w4xqmb",
    ],
    ratings: "⭐️⭐️⭐️⭐️",
    price: " 79.49",
    details:
      "Do you love cooking and baking but don't want to spend the money or have the space for all the tools you need? This 5-in-1 hand mixer from HOMCOM has everything you need to be a success in the kitchen. Achieve the consistency you need in your ingredients while saving tons of time with an immersion blender, chopper, whisker, dough kneader, and mixer. The all-in-one-hand blender saves space in your pantry instead of having five different kitchen appliances.",
    desc: "Do you love cooking and baking but don't want to spend the money or have the space for all the tools you need?",
    info: {
      reviews: 320,
      discount: 10,
      brand: "Homcom",
      availability: true,
      style: "Modern & Contemporary",
    },
  },
  {
    name: "Haden Heritage 700-Watt .7 cubic. foot Microwave with Settings and Timer in Light Blue Turquoise",
    img_url: "https://bit.ly/3Fflu57",
    imgArr: [
      "https://ak1.ostkcdn.com/images/products/is/images/direct/0b9b501787e2b779c815902dd8895979424bfa4f/Haden-Heritage-700-Watt-.7-cubic.-foot-Microwave-with-Settings-and-Timer-in-Turquoise-Blue.jpg?impolicy=medium",
      "https://ak1.ostkcdn.com/images/products/is/images/direct/2509054141bc60563c9eac0c07647d60e5470d97/Haden-Heritage-700-Watt-.7-cubic.-foot-Microwave-with-Settings-and-Timer-in-Turquoise-Blue.jpg?impolicy=medium",
      "https://ak1.ostkcdn.com/images/products/is/images/direct/b792abc61736f59ab8cd730e0a05a5acfca82232/Haden-Heritage-700-Watt-.7-cubic.-foot-Microwave-with-Settings-and-Timer-in-Turquoise-Blue.jpg?impolicy=medium",
      "https://ak1.ostkcdn.com/images/products/is/images/direct/e4b70ac556e68173454d68a3b9323b793f5ace10/Haden-Heritage-700-Watt-.7-cubic.-foot-Microwave-with-Settings-and-Timer-in-Turquoise-Blue.jpg?impolicy=medium",
      "https://ak1.ostkcdn.com/images/products/is/images/direct/ab7c9bf62010837315103582967d2d2c196f9ae2/Haden-Heritage-700-Watt-.7-cubic.-foot-Microwave-with-Settings-and-Timer-in-Turquoise-Blue.jpg?impolicy=medium",
    ],
    ratings: "⭐️⭐️⭐️⭐️",
    price: "125.29",
    details:
      "Simple yet sophisticated, our Haden Microwave features a .7 cubic foot capacity, 700W power, convenient defrost, reheat, cooking functions, and digital controls for easy use. It's perfect for everyday cooking, defrosting, and reheating. The sleek controls and unique, retro color make it an attractive addition to your countertop. Perfectly matches our Heritage light blue turquoise collection. ",
    desc: "Simple yet sophisticated, our Haden Microwave features a .7 cubic foot capacity, 700W power, convenient defrost, reheat, cooking functions, and digital controls for easy use",
    info: {
      reviews: 200,
      discount: 20,
      brand: "Haden",
      availability: true,
      style: "Formal",
    },
  },
  {
    name: "Professional 1.2 Cu.Ft. Microwave and Grill Oven",
    img_url:
      "https://ak1.ostkcdn.com/images/products/is/images/direct/cdbd1d1f6bbeb7024f2688357d87e2f4d3bb62ec/Professional-1.2-Cu.Ft.-Microwave-and-Grill-Oven.jpg?impolicy=medium",
    imgArr: [
      "https://ak1.ostkcdn.com/images/products/is/images/direct/a182c1e575bf952efd8ec91b7943640535978192/Professional-1.2-Cu.Ft.-Microwave-and-Grill-Oven.jpg?impolicy=medium",
      "https://ak1.ostkcdn.com/images/products/is/images/direct/38613072eb5380a4f704c3d4a3617c94c94d441a/Professional-1.2-Cu.Ft.-Microwave-and-Grill-Oven.jpg?impolicy=medium",
      "https://ak1.ostkcdn.com/images/products/is/images/direct/cdbd1d1f6bbeb7024f2688357d87e2f4d3bb62ec/Professional-1.2-Cu.Ft.-Microwave-and-Grill-Oven.jpg?impolicy=medium",
      "https://ak1.ostkcdn.com/images/products/is/images/direct/a182c1e575bf952efd8ec91b7943640535978192/Professional-1.2-Cu.Ft.-Microwave-and-Grill-Oven.jpg?impolicy=medium",
      "https://ak1.ostkcdn.com/images/products/is/images/direct/38613072eb5380a4f704c3d4a3617c94c94d441a/Professional-1.2-Cu.Ft.-Microwave-and-Grill-Oven.jpg?impolicy=medium",
    ],
    ratings: "⭐️⭐️⭐️⭐️",
    price: "139.98",
    details:
      "Bring a touch of class into your kitchen with the Farberware 1.2 Cubic Foot 1100 Watt Large Microwave Oven with Grill Function in Stainless Steel. Unique to this model is its dual cooking capabilities. Part grill, part microwave oven, this technology allows you to brown and crisp your food on the outside while maintaining a juicier inside.",
    desc: "Bring a touch of class into your kitchen with the Farberware 1.2 Cubic Foot 1100 Watt Large Microwave Oven with Grill Function in Stainless Stee",
    info: {
      reviews: 249,
      discount: 10,
      brand: "Farberware",
      availability: true,
      style: "Oriental ",
    },
  },
  {
    name: "Certified International - Tunisian Sunset 10.5-inch Dinner Plates (Set of 4)",
    img_url:
      "https://ak1.ostkcdn.com/images/products/10839801/Certified-International-Tunisian-Sunset-10.5-Dinner-Plates-Set-of-4-b50cb674-ee7f-437c-9825-f7601fa8cd8e_600.jpg?impolicy=medium",
    imgArr: [
      "https://ak1.ostkcdn.com/images/products/10839801/Certified-International-Tunisian-Sunset-10.5-Dinner-Plates-Set-of-4-668a9f4e-6d6c-419d-a94a-456a1757ff36_600.jpg?impolicy=medium",
    ],
    ratings: "⭐️⭐️⭐️⭐️⭐️",
    price: "55.49",
    details:
      "Turn your meal into a global affair with the beautiful detailing on this set of four Tunisian Sunset dinner plates. Hand-painted designs and textured patterning make these dinner plates pop against your table, and these durable ceramic plates are safe to go in the microwave and dishwasher for easy everyday use. ",
    desc: "Turn your meal into a global affair with the beautiful detailing on this set of four Tunisian Sunset dinner plates. Hand-painted designs and textured",
    info: {
      reviews: 500,
      discount: 20,
      brand: "Certified International ",
      availability: true,
      style: "Modern & Contemporary",
    },
  },
  {
    name: "Spode Blue Italian Earthenware Dinner Plate, 10-Inch - 10.5 inch",
    img_url:
      "https://ak1.ostkcdn.com/images/products/is/images/direct/2f299f515011c5bf52d0976b6aab660510ad7bf7/Spode-Blue-Italian-Earthenware-Dinner-Plate%2C-10-Inch.jpg?impolicy=medium",
    imgArr: [
      "https://ak1.ostkcdn.com/images/products/is/images/direct/35d1fe6ae207c95ae4c447088bb2c9947f69687d/Spode-Blue-Italian-Earthenware-Dinner-Plate%2C-10-Inch.jpg?impolicy=medium",
      "https://ak1.ostkcdn.com/images/products/is/images/direct/35d1fe6ae207c95ae4c447088bb2c9947f69687d/Spode-Blue-Italian-Earthenware-Dinner-Plate%2C-10-Inch.jpg?impolicy=medium",
      "https://ak1.ostkcdn.com/images/products/is/images/direct/87d2766c6e96869d4d8bb67b379333c9a6ef6698/Spode-Blue-Italian-Earthenware-Dinner-Plate%2C-10-Inch.jpg?impolicy=medium",
      "https://ak1.ostkcdn.com/images/products/is/images/direct/9153bbf775b820de7a23c045962884abdbce8a77/Spode-Blue-Italian-Earthenware-Dinner-Plate%2C-10-Inch.jpg?impolicy=medium",
      "https://ak1.ostkcdn.com/images/products/is/images/direct/c268b96241b6b1c7aa45b69928d2c68ca340465a/Spode-Blue-Italian-Earthenware-Dinner-Plate%2C-10-Inch.jpg?impolicy=medium",
    ],
    ratings: "⭐️⭐️⭐️⭐️⭐️",
    price: "24.00",
    details:
      "The Spode Blue Italian Dinner Plate is the perfect accompaniment to your dinner tablescape. Spode is well known for creating beautiful authentic Italian inspired dishes that elevate our kitchen counters and dining tables. The Blue Italian Collection was made possible by Josiah Spode's perfection of blue under-glaze printing in 1784 and features extensive, eclectic and imaginative blue and white tableware and cookware that takes you and your guests to the picturesque romantic countryside of Italy. Spode’s Blue Italian has something special for everyone, from gifts that will last a lifetime to the roasting dish that serves your family. Designed with the iconic Blue Italian design; this dinner plate features a finely detailed 18th century Imari Oriental border while the center design encompasses a stunning scene inspired by the Italian countryside. ",
    desc: "The Spode Blue Italian Dinner Plate is the perfect accompaniment to your dinner tablescape. Spode is well known for creating beautiful authentic Italian inspired dishes that elevate our kitchen counters and dining tables.",
    info: {
      reviews: 120,
      discount: 20,
      brand: "Spode ",
      availability: true,
      style: "Traditional",
    },
  },
  {
    name: "80-Pack Disposable Paper Plates, Lemon Party Supplies For Dinner Lunch, 9x 9",
    img_url:
      "https://ak1.ostkcdn.com/images/products/29744743/80-Pack-Disposable-Paper-Plates-Lemon-Party-Supplies-For-Dinner-Lunch-9-x-9-a328f6cc-2fb1-480d-8460-1eaad7db8da6_600.jpg?impolicy=medium",
    imgArr: [
      "https://ak1.ostkcdn.com/images/products/29744743/80-Pack-Disposable-Paper-Plates-Lemon-Party-Supplies-For-Dinner-Lunch-9-x-9-c021fe67-60ef-4bb4-aa1b-6e88b3c7143f_600.jpg?impolicy=medium",
      "https://ak1.ostkcdn.com/images/products/29744743/80-Pack-Disposable-Paper-Plates-Lemon-Party-Supplies-For-Dinner-Lunch-9-x-9-68e3f83c-ea72-4843-a83f-1be3ff422bbe_600.jpg?impolicy=medium",
      "https://ak1.ostkcdn.com/images/products/29744743/80-Pack-Disposable-Paper-Plates-Lemon-Party-Supplies-For-Dinner-Lunch-9-x-9-b4934123-ce49-47e9-8495-57e314eb4eab_600.jpg?impolicy=medium",
      "https://ak1.ostkcdn.com/images/products/29744743/80-Pack-Disposable-Paper-Plates-Lemon-Party-Supplies-For-Dinner-Lunch-9-x-9-d9df607e-ed19-4c29-9274-89d5391c57d4_600.jpg?impolicy=medium",
      "https://ak1.ostkcdn.com/images/products/29744743/80-Pack-Disposable-Paper-Plates-Lemon-Party-Supplies-For-Dinner-Lunch-9-x-9-f15d3174-8d4f-4515-8bf0-ef632bdb852f_600.jpg?impolicy=medium ",
    ],
    ratings: "⭐️⭐️⭐️⭐️⭐️",
    price: "27.49",
    details:
      " X Party Supply Disposable Plates 80-Count Paper Plates, Lemon Party Supplies for Appetizer, Lunch, Dinner, and Dessert, Brunch and Garden Party, 9 x 9 InchesSERVES 80: Includes enough plates for 80 guests; contains 80 paper plates featuring lemons with green leaves in a watercolor design. Plates are thick and rigid made of 350g whiteboard paper and won't fold while carrying food.SAFE AND ENVIRONMENTALLY FRIENDLY: 100% Food Grade and BPA-Free. Plates are made of environmentally friendly biodegradable paper. ",
    desc: "Disposable Plates - 80-Count Paper Plates, Lemon Party Supplies for Appetizer, Lunch, Dinner, and Dessert, Brunch and Garden Party, 9 x 9 Inches",
    info: {
      reviews: 60,
      discount: 20,
      brand: " demo",
      availability: true,
      style: "Casual",
    },
  },
  {
    name: "Certified International Seville 11 Melamine Dinner Plate, Set of 6 - 11 Dia",
    img_url:
      "https://ak1.ostkcdn.com/images/products/is/images/direct/5acaa8f98a934dc8b0ea0be8905eafdb59d3ab2a/Certified-International-Seville-11%22-Melamine-Dinner-Plate%2C-Set-of-6.jpg?impolicy=medium",
    imgArr: [
      "https://ak1.ostkcdn.com/images/products/is/images/direct/1d45d424788eff00d99eeef7168e0b9ff71aa2f9/Certified-International-Seville-11%22-Melamine-Dinner-Plate%2C-Set-of-6.jpg?impolicy=medium",
      "https://ak1.ostkcdn.com/images/products/is/images/direct/4c1f9da7da40b97e3987410646e3ebae582de256/Certified-International-Seville-11%22-Melamine-Dinner-Plate%2C-Set-of-6.jpg?impolicy=medium",
      "https://ak1.ostkcdn.com/images/products/is/images/direct/17c0086f611c258f326ef3fb3c029d5b2cd125c3/Certified-International-Seville-11%22-Melamine-Dinner-Plate%2C-Set-of-6.jpg?impolicy=medium",
    ],
    ratings: "⭐️⭐️⭐️⭐️⭐️",
    price: "62.09",
    details:
      " Certified International's Seville Set of 6 melamine dinner plates, reflects the bright colors and patterns of traditional Talavera style pottery, designed by the artist Nancy Green. Made of durable, heavyweight 100% melamine, each generously sized 11 diameter dinner plate is a very special addition to your indoor or outdoor dining table. Order the rest of the matching melamine dinnerware and serveware!",
    desc: "Certified International's Seville Set of 6 melamine dinner plates, reflects the bright colors and patterns of traditional Talavera style pottery",
    info: {
      reviews: 200,
      discount: 10,
      brand: "Certified International ",
      availability: true,
      style: "Casual, Southwestern",
    },
  },
  {
    name: "Certified International Bee Sweet 9 Melamine Salad/Dessert Plates, Set of 6 - 9Dia",
    img_url:
      "https://ak1.ostkcdn.com/images/products/is/images/direct/6c0ccbf426351ca253859a716f9402c6377daa3e/Certified-International-Bee-Sweet-9%22-Melamine-Salad-Dessert-Plates%2C-Set-of-6.jpg?impolicy=medium",
    imgArr: [
      "https://ak1.ostkcdn.com/images/products/is/images/direct/a0b485ba1afcaaa501d2f02121a321898394c6b6/Certified-International-Bee-Sweet-9%22-Melamine-Salad-Dessert-Plates%2C-Set-of-6.jpg?impolicy=medium",
      "https://ak1.ostkcdn.com/images/products/is/images/direct/face5280968de42ba2c507bea63d10032ef2053a/Certified-International-Bee-Sweet-9%22-Melamine-Salad-Dessert-Plates%2C-Set-of-6.jpg?impolicy=medium",
      "https://ak1.ostkcdn.com/images/products/is/images/direct/0f5136dd4cbe12c96fab73a6dc073ba31400d126/Certified-International-Bee-Sweet-9%22-Melamine-Salad-Dessert-Plates%2C-Set-of-6.jpg?impolicy=medium",
    ],
    ratings: "⭐️⭐️⭐️⭐️⭐️",
    price: "52.99",
    details:
      "Bee Sweet is a charming 6 pc Melamine salad plate set from Certified International designed by the popular artist Susan Winget. Featuring busy bees and lovely flowers for your indoor and outdoor dining, this durable heavyweight 100% melamine set will delight your family and guests. Set includes 6- 9  diameter salad plates. Be sure to get the coordinating Bee Sweet melamine dinnerware and serveware. Great to mix and match with the Bee Sweet ceramic collection as well. ",
    desc: "Bee Sweet is a charming 6 pc Melamine salad plate set from Certified International designed by the popular artist Susan Winget.",
    info: {
      reviews: 60,
      discount: 60,
      brand: "Certified International ",
      availability: true,
      style: "Casual, Country",
    },
  },

  {
    name: "DOWAN Porcelain Matte Print 8 Dinner Plate",
    img_url:
      "https://ak1.ostkcdn.com/images/products/is/images/direct/30cd0011a65010c8adde7e86072f6375685e54f8/DOWAN-Porcelain-Matte-Print-8%22-Dinner-Plate.jpg?impolicy=medium",
    imgArr: [
      "https://ak1.ostkcdn.com/images/products/is/images/direct/969a258ae65de00c2c25bdcab39bc9f5bcd397d8/DOWAN-Porcelain-Matte-Print-8%22-Dinner-Plate.jpg?impolicy=medium",
      "https://ak1.ostkcdn.com/images/products/is/images/direct/178e31996f1e78189441f8b6ba405a06565cbf06/DOWAN-Porcelain-Matte-Print-8%22-Dinner-Plate.jpg?impolicy=medium",
      "https://ak1.ostkcdn.com/images/products/is/images/direct/3d43a0721e25cc5a2e66ba3218d5edadb79a8381/DOWAN-Porcelain-Matte-Print-8%22-Dinner-Plate.jpg?impolicy=medium",
      "https://ak1.ostkcdn.com/images/products/is/images/direct/6c8bfa24871e7226cbdf1fb751fc1aac885c92c9/DOWAN-Porcelain-Matte-Print-8%22-Dinner-Plate.jpg?impolicy=medium",
      "https://ak1.ostkcdn.com/images/products/is/images/direct/30cd0011a65010c8adde7e86072f6375685e54f8/DOWAN-Porcelain-Matte-Print-8%22-Dinner-Plate.jpg?impolicy=medium",
    ],
    ratings: "⭐️⭐️⭐️⭐️⭐️",
    price: "49.99",
    details:
      " Modern plate set-beige matte print design. The perfect addition to your Thanksgiving or Christmas dinner table. Modern Design: no matter for everyday use or entertaining, these plate sets will always present your food with amazing grace. You can use it for an appetizer, dessert, salad, snack, bread. Great for dinner meals instead of larger plates as they help you to eat smaller portions. You can monitor portion control to keep your body. A nice gift set for your friends and family. It makes your gifts to friends and family stand apart. These appetizer plates can be stacked together for easy storage, it won't take up much space in your kitchen. They've held up great in the dishwasher and because of the curved design, they stand up properly for a better wash than flat dinner plates. Elegant and simple in form, suitable for the dinner table, family party, top-grade restaurant, or almost daily. Your food will be the main focal point and provide elegance for the table setting.",
    desc: "Modern plate set-beige matte print design. The perfect addition to your Thanksgiving or Christmas dinner table. ",
    info: {
      reviews: 200,
      discount: 5,
      brand: " volt",
      availability: true,
      style: "Modern & Contemporary",
    },
  },
];

console.log(prodArr.length);
